# Generated by Django 5.2.3 on 2025-06-29 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_letter', models.CharField(max_length=10, unique=True)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('points', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-max_score'],
            },
        ),
        migrations.CreateModel(
            name='SampleSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='SampleKCSESubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(choices=[('Paper 1', 'Paper 1'), ('Paper 2', 'Paper 2'), ('Paper 3', 'Paper 3')], max_length=20)),
                ('max_score', models.PositiveIntegerField()),
                ('percentage_weight', models.FloatField(help_text='Percentage weight towards final grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplekcsesubjectpaper_set', to='sample.samplesubject')),
            ],
            options={
                'verbose_name': 'KCSE Subject Paper',
                'verbose_name_plural': 'KCSE Subject Papers',
                'unique_together': {('subject', 'paper_name')},
            },
        ),
    ]
