# Generated by Django 5.2.3 on 2025-07-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_details', models.JSONField()),
                ('data', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['school_details', 'received_at', 'is_processed'], name='analytics_a_school__a56d8a_idx')],
            },
        ),
    ]
