# Generated by Django 5.2.3 on 2025-11-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningLevels',
            new_name='LearningLevel',
        ),
    ]
